name: Video CloZett MVP Build
on: [push]

jobs:
build-test:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4
- name: Send Slack
run: |
curl -X POST -H 'Content-type: application/json' --data "{"text": "🚀 Video CloZett 疎通成功！\nようやく開通しました。"}" ${{ secrets.SLACK_WEBHOOK_URL }}
